# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: SSH and deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.TESTNET_HOST }}
        username: ec2-user
        key: ${{ secrets.TESTNET_SSH_KEY }}
        script: |
          if [ ! -d "my-app" ]; then git clone https://github.com/<your-username>/<your-repo>.git my-app; fi
          cd my-app
          git checkout testnet
          git pull origin testnet
          npm install
          pm2 start app.js --name testnet-app || pm2 restart testnet-app
          
